### ISSUE TITLE
Chat List Moderation

### ISSUE THREAD

**Issue by wlcrumb** [MTU-2019-Fall-CS3141-4711/Project#17]
Add a feature where you can click on a username in the chat list and get a popup of moderation options including ban and promote.

**Comment by Parsonswy** [comment]
Buttons in prod ( re #38 ) and the information is replicated through Firebase, however the client doesn't actually react to being banned, nor will Firebase / RealtimeDB reject requests from banned users yet.
This will come, hopefully, in sprint 4 when we update the database auth rules.
