### ISSUE TITLE
Video Queue User does not display right name

### ISSUE THREAD

**Issue by doboggio** [MTU-2019-Fall-CS3141-4711/Project#32]
Currently it pulls the name of the user _viewing_ the page, not the name of the user that added to the queue.

**Comment by Parsonswy** [comment]
Sorry, this needs the [RoomState](https://github.com/MTU-2019-Fall-CS3141-4711/Project/blob/master/js/models/RoomState.js) equivalent to get usernames for other users in the room.
```javascript
RoomState.getUsername( userid_of_que-er );
```
