### ISSUE TITLE
Informational Chat Messages for Auth Events

### ISSUE THREAD

**Issue by Parsonswy** [MTU-2019-Fall-CS3141-4711/Project#51]
Send a message in the chat to the room when a user is banned / pardoned and when a user is promoted / demoted.
To make this super nice we would have two different chat styles, one that was more subtle for informational messages and maybe with grey, italic text. The less clean option is just have the user that performed the action send the message as a normal chat message. IE if Frank bans Joseph, then we use **Frank**: has banned Joseph.

**Comment by wlcrumb** [comment]
I set up the "less clean" option. I will work on the custom formatting.

**Comment by wlcrumb** [comment]
I implemented the custom formatting.
